### ISSUE TITLE
SplitPackage should write warning \ errors to the error stream

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#51] opened 2016-05-01 02:29 UTC
The CI picks up any messages to the error stream and adds it to the summary.

**Comment by javiercn** [comment] 2016-05-01 02:30
Is there a way to achieve this with our current logging capabilities? We use the standard ASP.NET logging infrastructure

**Comment by Eilon** [comment] 2016-05-09 17:23
I think I chatted with @javiercn last week. I vaguely recall there being some good reason that we didn't have the ConsoleLogger write to the error stream. Unfortunately I don't recall what that reason was.

**Comment by javiercn** [comment] 2016-05-09 17:38
@Eilon I couldn't find anything on the list of issues. I believe that writing errors to the error stream is the right thing to do too. It allows whoever launches the process to surface these errors independently if they choose to do so and by default it will be redirected to the standard output, so it's the same behavior by default but is more flexible. Writing a different logger to achieve this is not acceptable IMO as it requires modifying the program which is something you might not be able to in all scenarios.

**Comment by Eilon** [comment] 2016-05-09 17:56
Yeah I don't think there was ever an issue logged, it was from a discussion.

**Comment by Eilon** [comment] 2016-10-28 20:59
@pranavkm @javiercn is this still useful? Have we had any issues with this that we need/want to resolve?

**Comment by pranavkm** [comment] 2016-10-28 21:02
It'll be nice to have. Right now you need to look at the build log to see the failure. The alternative is to wrap error messages using TeamCity specific constructs but this would be the easier of the two.

**Comment by javiercn** [comment] 2016-12-06 01:08
Split packages uses the console logger, so I would argue that we should fix the console logger, not this.

**Comment by Eilon** [comment] 2016-12-09 19:26
Per my earlier comment, we need to be careful about that.

**Comment by javiercn** [comment] 2016-12-09 20:40
@Eilon Errors should go to the error stream on the Console logger for sure, warnings is debatable, but can be configurable. Last time I look into this, I didn't see any compelling reason not to do it that way. The reason its done that way is so that any app that wants to filter errors can just read from the error stream instead of having to parse the output. Its up to whomever is running the app (the console or another program) to decide what to do with the error output stream, either redirect it to a specific location or do nothing and then it gets merged with the standard output. I really think this is the responsibility of the logger and not of this specific tool.

**Comment by Eilon** [comment] 2016-12-12 17:58
Though I agree in principal that errors should be written out to the error stream, I don't think that in practice that is always the best behavior. But, like I said, I don't recall the exact reason. It may have been due to something about running `foo.exe > output.txt` and that if you do that, perhaps you don't see the error output at all, and you see only the non-error output.

**Comment by javiercn** [comment] 2016-12-12 19:55
@Eilon you would see the errors in that case. The error stream is redirected to the output stream automatically unless you redirect it to another stream explicitly. If we can't find the reason not to do this, can it be that wasn't there as clear/important as we thought originally?

**Comment by Eilon** [comment] 2016-12-13 00:56
Maybe the problem was that if you capture both streams separately, there is no way to know how to interleave them? That is, you have one stream with all errors, one with all non-errors, and there's no way to know the sequence in which they happened? If it's all always in one stream, you have the output "as it was intended."

**Comment by Eilon** [comment] 2016-12-13 00:56
(I'm not saying any of this was the reason - I just vaguely recall there being some problem with it.)

**Comment by Eilon** [comment] 2017-04-06 20:33
Closing because we are not planning to do this. Having to look at the log file is not unreasonable.

**Closed by Eilon** 2017-04-06 20:33 UTC
Labels: 1 - Ready, task
