### ISSUE TITLE
Test target randomly fails for no discernible reason

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#539] opened 2018-01-03 20:37 UTC
Spoke to @ryanbrandenburg about failures on the CI, saw something similar on AppVeyor (https://ci.appveyor.com/project/aspnetci/mvc/build/1.0.9754)

```
Total tests: 9182. Passed: 9161. Failed: 0. Skipped: 21.
Test Run Successful.
Test execution time: 1.0834 Minutes
C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15651\modules\vstest\module.targets(103,5): error : Test group UnitTests/net461 failed with exit code '1'. [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15651\KoreBuild.proj]
Build FAILED.
C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15651\modules\vstest\module.targets(103,5): error : Test group UnitTests/net461 failed with exit code '1'. [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15651\KoreBuild.proj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:12:00.28
```

Given our goal to keep the CI green (https://github.com/aspnet/Mvc/issues/7172), we should figure out what's causing this failure.

**Comment by natemcmaster** [comment] 2018-01-03 20:38
Is it only happening in AppVeyor?

**Comment by pranavkm** [comment] 2018-01-03 20:39
Also saw this on TeamCity: http://aspnetci/viewLog.html?buildId=378905&tab=buildResultsDiv&buildTypeId=Lite_Mvc

**Comment by natemcmaster** [comment] 2018-01-03 20:40
My best guess is that vstest is failing at the end of the test run. Could be an issue in the TRX logger, the appveyor test result publisher, testhost, etc. Gathering more vstest logs would be the best way to investigate. `dotnet vstest --Diag`

**Comment by pranavkm** [comment] 2018-01-03 21:51
@natemcmaster one more failure here - https://ci.appveyor.com/project/aspnetci/routing/build/1.0.911

**Comment by pranavkm** [comment] 2018-01-09 23:11
More related failure:

```
dotnet.exe : Unable to send data over channel.
At C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15661\scripts\common.psm1:7 char:5
+     & $_cmd @args
+     ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to send data over channel.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15661\modules\vstest\module.targets(106,5): error : Test group UnitTests/net461 failed with exit code '1'. [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.1.0-preview1-15661\KoreBuild.proj]
Build FAILED.
```

@Eilon could we triage this issue for preview1?

**Comment by Eilon** [comment] 2018-01-09 23:42
Sure thing, we'll pick it up in triage this afternoon.

**Comment by Eilon** [comment] 2018-01-10 00:22
Parking on @ryanbrandenburg to see if the new diagnostics he enabled will shed more light on this.

**Comment by ryanbrandenburg** [comment] 2018-01-11 19:49
We seem to have gotten a reproduction of this!
[UnitTests-net461-19172.txt](https://github.com/aspnet/BuildTools/files/1623917/UnitTests-net461-19172.txt)

Of particular interest in there to me is:
```
Line 250: TpTrace Error: 0 : 1580, 18, 2018/01/10, 21:50:46.501, 441714436263, vstest.console.dll, Socket: Message loop: failed to receive message due to socket error System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
```
and
```
TpTrace Error: 0 : 1580, 14, 2018/01/10, 21:50:55.937, 441808791910, vstest.console.dll, Exception: System.IO.IOException
	Message: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine.
```
I seem to remember us already having an issue for this on the vstest repo but I can't find it now. @natemcmaster  do you remember where that is (if I'm not crazy).

**Comment by natemcmaster** [comment] 2018-01-11 19:58
I couldn't find it. Let's forward this to https://github.com/microsoft/vstest

**Comment by Eilon** [comment] 2018-02-06 22:50
Anything more we think we can do for preview1? If not, let's move to preview2.

**Comment by ryanbrandenburg** [comment] 2018-02-06 23:34
I haven't seen this happen in a while, let's move to preview2 and I'll keep an eye out.

**Comment by mikeharder** [comment] 2018-02-16 22:42
I think this is another repro: http://aspnetci/viewLog.html?buildId=408027&buildTypeId=Lite_KestrelHttpServer&tab=buildLog&_focus=32720

**Comment by ryanbrandenburg** [comment] 2018-02-24 00:44
I updated our tests on the CI not to use `--blame` like the VSTest guys asked, now we're just waiting for it to happen again.

**Comment by Eilon** [comment] 2018-03-07 00:21
Moving to Backlog because there is no action to take at this time. If at some point we see this failure again we can look back to this bug for details on how to proceed.

**Comment by natemcmaster** [comment] 2019-04-30 17:29
Closing. This issue has gone stale.

**Closed by natemcmaster** 2019-04-30 17:29 UTC
Labels: 1 - Ready, cost: M, task
