### ISSUE TITLE
ApiCheck: Tool fails when an empty constructor is removed and replaced by a default constructor

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#174] opened 2017-02-14 17:50 UTC

**Comment by dougbu** [comment] 2017-03-25 20:08
@pranavkm I was curious and played with a few cases. Couldn't make the tool spit out errors when it shouldn’t. But, API Check seems to ignore removal of a parameterless constructor _sometimes_. Is that what you meant?

##### Details
- The tool correctly ignored removing the sole parameterless constructor in a couple of classes.
- It also usually displayed the correct errors when removing the parameterless constructor if others exist. This make sense because the compiler only adds a default constructor when none are defined.
- But, API Check was strangely silent when I removed the parameterless constructor in https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Formatters/FormatterCollection.cs. Perhaps the issue is specific to generic classes?

**Comment by dougbu** [comment] 2017-03-25 22:09
@pranavkm I checked again. https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Formatters/FormatterCollection.cs didn't have a parameterless constructor when the baselines were generated. I have not reproduced this issue after a few tries. What am I missing?

**Comment by pranavkm** [comment] 2017-03-25 22:49
I saw this when I attempted to remove the ctor from https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorPage.cs#L28. We used to initialize a field in the ctor in the past and I moved it to the field. However, removing the ctor caused ApiCheck to fail.

**Comment by dougbu** [comment] 2017-03-26 00:38
I think we can close this. Did the same thing in current `dev` branch then ran `dotnet msbuild /t:Pack` in the directory. Everybody was mildly satisfied, happy even.

**Comment by dougbu** [comment] 2017-03-26 00:45
Ah. API Check is disabled there now. Saw a few errors about removed members when I re-enabled it.

But, the error displayed about `public abstract class Microsoft.AspNetCore.Mvc.Razor.RazorPage : Microsoft.AspNetCore.Mvc.Razor.IRazorPage => public .ctor()` is __correct__. The default constructor is `protected` because this is an `abstract` class. The one you and I removed was `public`.

**Comment by Eilon** [comment] 2017-04-06 21:03
Closing because this seems fine.

**Closed by Eilon** 2017-04-06 21:03 UTC
