### ISSUE TITLE
ApiCheck doesn't seem to run on macOS

### ISSUE THREAD

**Issue by halter73** [aspnet/BuildTools#620] opened 2018-03-23 23:13 UTC
### Repro steps:

1. Clone aspnet/KestrelHttpServer@2dc1858 on macOS
2. Remove [this line](https://github.com/aspnet/KestrelHttpServer/blob/2dc1858f90548e18f5f066c7f4202cabd6309f0c/src/Kestrel.Transport.Libuv/Kestrel.Transport.Libuv.csproj#L12) from Kestrel.Transport.Libuv.csproj to enable ApiCheck for the project.
3. Run build.sh from the root of the repo with no extra parameters.

### Expected behavior

The ApiCheck should fail with the following error like it does on Windows:

```
C:\Users\shalter\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview2-15742\build\ApiCheck.targets(53,5): error : ERROR: Verifying breaking changes for framework netstandard2.0 failed. [G:\dev\aspnet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Kestrel.Transport.Libuv.csproj]


  The following types have one or more members removed from them.

      public class Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransportFactory : Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ITransportFactory
          public Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ITransport Create(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IEndPointInformation endPointInformation, Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionHandler handler)



  Following is the list of exclusions that either need to be added to the list of breaking changes, or the breaking changes themselves need to be reverted:
  Successfully created package 'G:\dev\aspnet\KestrelHttpServer\artifacts\build\Microsoft.AspNetCore.Connections.Abstractions.2.1.0-preview3-t000.nupkg'.
  Successfully created package 'G:\dev\aspnet\KestrelHttpServer\artifacts\build\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.2.1.0-preview3-t000.nupkg'.
  [
    {
      "TypeId": "public class Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.LibuvTransportFactory : Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ITransportFactory",
      "MemberId": "public Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.ITransport Create(Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IEndPointInformation endPointInformation, Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.Internal.IConnectionHandler handler)",
      "Kind": "Removal"
    }
  ]

  The process for breaking changes is described in: https://github.com/aspnet/Home/wiki/Engineering-guidelines#breaking-changes
  The process to add an exclusion to this tool is described in: https://github.com/aspnet/BuildTools/wiki/Api-Check#apicheck-exceptions
```

### Actual Behavior

The full build completes successfully.

### Extra Note

`dotnet build /t:ApiCheck` in `src/Kestrel.Transport.Libuv/` on macOS also succeeds when it should fail with the same error.

@javiercn @natemcmaster

**Comment by javiercn** [comment] 2018-03-23 23:20
We only run it on windows, that's by design.

**Comment by Eilon** [comment] 2018-03-24 23:45
@javiercn - what was the reason?

**Comment by javiercn** [comment] 2018-03-25 01:08
I don't remember the exact issues, but it was low value given the fact that we don't have platform specific APIs. When/if we update the tool to use a different approach this will be solved. There's an old issue tracking this, but I can't find it

**Comment by Eilon** [comment] 2018-03-25 05:59
Ok that's fine, so closing for now.

**Closed by Eilon** 2018-03-25 05:59 UTC
